import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://mcelqinrwenlsxsyoqxs.supabase.co'\;
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZWxxaW5yd2VubHN4c3lvcXhzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDEyNTM0NCwiZXhwIjoyMDk1NzAxMzQ0fQ.9Xc4q4n7ppMOBjlnuhU4efJK0831Uqkx9j79zCGqBvo';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZWxxaW5yd2VubHN4c3lvcXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxMjUzNDQsImV4cCI6MjA5NTcwMTM0NH0.1Yswl1yQDzoMgjGV9I44kLL54u_7IpyLobelHxxlT-c';

export const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
